/*
* generated by Xtext
*/
package de.tu_bs.cs.isf.deltamsc;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class DeltaMSCUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return de.tu_bs.cs.isf.deltamsc.ui.internal.DeltaMSCActivator.getInstance().getInjector("de.tu_bs.cs.isf.deltamsc.DeltaMSC");
	}
	
}
