/**
 * generated by Xtext
 */
package de.tu_bs.cs.isf.splregtest.xtext.mapping.validation;

import de.tu_bs.cs.isf.splregtest.xtext.mapping.validation.AbstractMapsCompSmValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class MapsCompSmValidator extends AbstractMapsCompSmValidator {
}
