/*
 * generated by Xtext
 */
package org.xtext.deltarx.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class DeltarxUiModule extends org.xtext.deltarx.ui.AbstractDeltarxUiModule {
	public DeltarxUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
