/**
 * generated by Xtext
 */
package de.tu_bs.cs.isf.splregtest.xtext.mapping.scoping;

import org.eclipse.xtext.scoping.impl.AbstractDeclarativeScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class MapsCompSmScopeProvider extends AbstractDeclarativeScopeProvider {
}
