/*
 * generated by Xtext
 */
package de.tu_bs.cs.isf.splregtest.xtext.mapping;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class MapsCompSmStandaloneSetup extends MapsCompSmStandaloneSetupGenerated{

	public static void doSetup() {
		new MapsCompSmStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

