/*
 * generated by Xtext
 */
package de.tu_bs.cs.isf.splregtest.xtext.mapping;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MapsCompSmRuntimeModule extends de.tu_bs.cs.isf.splregtest.xtext.mapping.AbstractMapsCompSmRuntimeModule {

}
