/*
 * generated by Xtext
 */
package de.tu_bs.cs.isf.deltamsc.ui.contentassist

import de.tu_bs.cs.isf.deltamsc.ui.contentassist.AbstractDeltaMSCProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class DeltaMSCProposalProvider extends AbstractDeltaMSCProposalProvider {
}
