/*
* generated by Xtext
*/
package org.xtext.deltarx;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class DeltarxUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.xtext.deltarx.ui.internal.DeltarxActivator.getInstance().getInjector("org.xtext.deltarx.Deltarx");
	}
	
}
