/*
 * generated by Xtext
 */
package de.tu_bs.cs.isf.splregtest.xtext.mapping.ui.contentassist

import de.tu_bs.cs.isf.splregtest.xtext.mapping.ui.contentassist.AbstractMapsCompSmProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class MapsCompSmProposalProvider extends AbstractMapsCompSmProposalProvider {
}
