/*
* generated by Xtext
*/
package de.tu_bs.cs.isf.deltamsc.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import de.tu_bs.cs.isf.deltamsc.services.DeltaMSCGrammarAccess;

public class DeltaMSCParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private DeltaMSCGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected de.tu_bs.cs.isf.deltamsc.parser.antlr.internal.InternalDeltaMSCParser createParser(XtextTokenStream stream) {
		return new de.tu_bs.cs.isf.deltamsc.parser.antlr.internal.InternalDeltaMSCParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "DeltaMSC";
	}
	
	public DeltaMSCGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(DeltaMSCGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
