/*
* generated by Xtext
*/
package de.tu_bs.cs.isf.deltamsc.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class DeltaMSCAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("de/tu_bs/cs/isf/deltamsc/parser/antlr/internal/InternalDeltaMSC.tokens");
	}
}
