/*
 * generated by Xtext
 */
package de.tu_bs.cs.isf.splregtest.xtext.mapping.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class MapsCompSmUiModule extends de.tu_bs.cs.isf.splregtest.xtext.mapping.ui.AbstractMapsCompSmUiModule {
	public MapsCompSmUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
