/*
 * generated by Xtext
 */
package de.tu_bs.cs.isf.deltamsc;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class DeltaMSCRuntimeModule extends de.tu_bs.cs.isf.deltamsc.AbstractDeltaMSCRuntimeModule {

}
