/*
* generated by Xtext
*/
package de.tu_bs.cs.isf.deltamsc;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class DeltaMSCStandaloneSetup extends DeltaMSCStandaloneSetupGenerated{

	public static void doSetup() {
		new DeltaMSCStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

