/*
* generated by Xtext
*/
package org.xtext.deltarx.ui.contentassist;

import org.xtext.deltarx.ui.contentassist.AbstractDeltarxProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class DeltarxProposalProvider extends AbstractDeltarxProposalProvider {

}
