/*
 * generated by Xtext
 */
package org.xtext.deltarx.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.xtext.deltarx.ui.internal.DeltarxActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class DeltarxExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return DeltarxActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return DeltarxActivator.getInstance().getInjector(DeltarxActivator.ORG_XTEXT_DELTARX_DELTARX);
	}
	
}
