/*
 * generated by Xtext
 */
package de.tu_bs.cs.isf.splregtest.xtext.mapping.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import de.tu_bs.cs.isf.splregtest.xtext.mapping.ui.internal.MapsCompSmActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MapsCompSmExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return MapsCompSmActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return MapsCompSmActivator.getInstance().getInjector(MapsCompSmActivator.DE_TU_BS_CS_ISF_SPLREGTEST_XTEXT_MAPPING_MAPSCOMPSM);
	}
	
}
