/*
 * generated by Xtext
 */
package de.tu_bs.cs.isf.splregtest.xtext.mapping.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import de.tu_bs.cs.isf.splregtest.xtext.mapping.services.MapsCompSmGrammarAccess;

public class MapsCompSmParser extends AbstractContentAssistParser {
	
	@Inject
	private MapsCompSmGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected de.tu_bs.cs.isf.splregtest.xtext.mapping.ui.contentassist.antlr.internal.InternalMapsCompSmParser createParser() {
		de.tu_bs.cs.isf.splregtest.xtext.mapping.ui.contentassist.antlr.internal.InternalMapsCompSmParser result = new de.tu_bs.cs.isf.splregtest.xtext.mapping.ui.contentassist.antlr.internal.InternalMapsCompSmParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getMappingAccess().getGroup(), "rule__Mapping__Group__0");
					put(grammarAccess.getComponentAccess().getGroup(), "rule__Component__Group__0");
					put(grammarAccess.getBSMAccess().getGroup(), "rule__BSM__Group__0");
					put(grammarAccess.getMappingAccess().getNameAssignment_1(), "rule__Mapping__NameAssignment_1");
					put(grammarAccess.getMappingAccess().getComponentsAssignment_3(), "rule__Mapping__ComponentsAssignment_3");
					put(grammarAccess.getComponentAccess().getNameAssignment_1(), "rule__Component__NameAssignment_1");
					put(grammarAccess.getComponentAccess().getBsmsAssignment_3(), "rule__Component__BsmsAssignment_3");
					put(grammarAccess.getBSMAccess().getNameAssignment_1(), "rule__BSM__NameAssignment_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			de.tu_bs.cs.isf.splregtest.xtext.mapping.ui.contentassist.antlr.internal.InternalMapsCompSmParser typedParser = (de.tu_bs.cs.isf.splregtest.xtext.mapping.ui.contentassist.antlr.internal.InternalMapsCompSmParser) parser;
			typedParser.entryRuleMapping();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public MapsCompSmGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(MapsCompSmGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
