/*
* generated by Xtext
*/
package org.xtext.deltarx.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class DeltarxOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
