/*
 * generated by Xtext
 */
package de.tu_bs.cs.isf.deltamsc.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class DeltaMSCUiModule extends de.tu_bs.cs.isf.deltamsc.ui.AbstractDeltaMSCUiModule {
	public DeltaMSCUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
