/*
 * generated by Xtext
 */
package org.xtext.deltarx;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class DeltarxRuntimeModule extends org.xtext.deltarx.AbstractDeltarxRuntimeModule {

}
