/*
 * generated by Xtext
 */
package de.tu_bs.cs.isf.splregtest.xtext.mapping.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import de.tu_bs.cs.isf.splregtest.xtext.mapping.services.MapsCompSmGrammarAccess;

public class MapsCompSmParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private MapsCompSmGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected de.tu_bs.cs.isf.splregtest.xtext.mapping.parser.antlr.internal.InternalMapsCompSmParser createParser(XtextTokenStream stream) {
		return new de.tu_bs.cs.isf.splregtest.xtext.mapping.parser.antlr.internal.InternalMapsCompSmParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Mapping";
	}
	
	public MapsCompSmGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(MapsCompSmGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
