/*
 * generated by Xtext
 */
package de.tu_bs.cs.isf.splregtest.xtext.mapping;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class MapsCompSmUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return de.tu_bs.cs.isf.splregtest.xtext.mapping.ui.internal.MapsCompSmActivator.getInstance().getInjector("de.tu_bs.cs.isf.splregtest.xtext.mapping.MapsCompSm");
	}
	
}
